// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBos-ar1MeP9qRIi3Gn2PlxXwlHReQ3f18',
    appId: '1:1012043894026:web:6894d29df3721d93f0fef3',
    messagingSenderId: '1012043894026',
    projectId: 'nupro-63fb3',
    authDomain: 'nupro-63fb3.firebaseapp.com',
    storageBucket: 'nupro-63fb3.firebasestorage.app',
    measurementId: 'G-J7YDENCTQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGj0NbZsH7BGcnaZlbp9zNEd0_o-fSB10',
    appId: '1:1012043894026:android:1a7ccb38039c81b3f0fef3',
    messagingSenderId: '1012043894026',
    projectId: 'nupro-63fb3',
    storageBucket: 'nupro-63fb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3BHvcQhrqTDQgzh5KXCqy5qh42r9e7dU',
    appId: '1:1012043894026:ios:4076678550acfa1bf0fef3',
    messagingSenderId: '1012043894026',
    projectId: 'nupro-63fb3',
    storageBucket: 'nupro-63fb3.firebasestorage.app',
    iosBundleId: 'com.example.susPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3BHvcQhrqTDQgzh5KXCqy5qh42r9e7dU',
    appId: '1:1012043894026:ios:4076678550acfa1bf0fef3',
    messagingSenderId: '1012043894026',
    projectId: 'nupro-63fb3',
    storageBucket: 'nupro-63fb3.firebasestorage.app',
    iosBundleId: 'com.example.susPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBos-ar1MeP9qRIi3Gn2PlxXwlHReQ3f18',
    appId: '1:1012043894026:web:06f8ec7e42914882f0fef3',
    messagingSenderId: '1012043894026',
    projectId: 'nupro-63fb3',
    authDomain: 'nupro-63fb3.firebaseapp.com',
    storageBucket: 'nupro-63fb3.firebasestorage.app',
    measurementId: 'G-J8323E0RZM',
  );

}