// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiF3px5O17I8zKHLKNiAeCX8cZaClAqrg',
    appId: '1:1012043894026:web:689ba06ffd2bd1aaf0fef3',
    messagingSenderId: '1012043894026',
    projectId: 'nupro-63fb3',
    authDomain: 'nupro-63fb3.firebaseapp.com',
    storageBucket: 'nupro-63fb3.firebasestorage.app',
    measurementId: 'G-N2LMMCE6M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGj0NbZsH7BGcnaZlbp9zNEd0_o-fSB10',
    appId: '1:1012043894026:android:24ef4c27d1f5f5fbf0fef3',
    messagingSenderId: '1012043894026',
    projectId: 'nupro-63fb3',
    storageBucket: 'nupro-63fb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3BHvcQhrqTDQgzh5KXCqy5qh42r9e7dU',
    appId: '1:1012043894026:ios:e69e48fa1ab7e142f0fef3',
    messagingSenderId: '1012043894026',
    projectId: 'nupro-63fb3',
    storageBucket: 'nupro-63fb3.firebasestorage.app',
    iosBundleId: 'mn.nexusinfinity.nupro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3BHvcQhrqTDQgzh5KXCqy5qh42r9e7dU',
    appId: '1:1012043894026:ios:e69e48fa1ab7e142f0fef3',
    messagingSenderId: '1012043894026',
    projectId: 'nupro-63fb3',
    storageBucket: 'nupro-63fb3.firebasestorage.app',
    iosBundleId: 'mn.nexusinfinity.nupro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiF3px5O17I8zKHLKNiAeCX8cZaClAqrg',
    appId: '1:1012043894026:web:27afa7b0999ccfc3f0fef3',
    messagingSenderId: '1012043894026',
    projectId: 'nupro-63fb3',
    authDomain: 'nupro-63fb3.firebaseapp.com',
    storageBucket: 'nupro-63fb3.firebasestorage.app',
    measurementId: 'G-2BET3MTTD1',
  );

}